import type { Recall } from "@/lib/types";

export const recallFixture: Recall = {
  id: "9111d5c1-d82d-5052-9161-f8b32d481860",
  source: "fda",
  source_recall_id: "H-1237-2026",
  record_type: "recall",
  category: "food",
  product_name: "KC Everyday Mac & Cheese",
  brand: "Kerry",
  recalling_firm: "Kerry, Inc.",
  description: "Prepared macaroni and cheese product.",
  recall_reason: "Potential contamination with Salmonella.",
  classification: "Class II",
  severity: null,
  status: "Ongoing",
  recall_date: "2026-07-14",
  reported_at: "2026-08-19",
  source_updated_at: null,
  distribution_pattern: "Distributed in select U.S. states.",
  product_code_info: "Lot 42; UPC 20609055",
  product_items: [],
  establishment_numbers: [],
  source_documents: [],
  states: ["NY", "PA"],
  upc_codes: ["20609055"],
  lot_numbers: ["LOT 42"],
  source_url: "https://api.fda.gov/food/enforcement.json?search=recall_number:H-1237-2026",
  created_at: "2026-08-30T12:00:00Z",
  updated_at: "2026-08-30T12:00:00Z",
};

export const fsisAlertFixture: Recall = {
  ...recallFixture,
  id: "a64540a1-3af5-5c44-b0ea-0a854f23bb98",
  source: "usda_fsis",
  source_recall_id: "PHA-08082026-01",
  record_type: "public_health_alert",
  product_name: "Meat and poultry products containing recalled jalapeños",
  brand: null,
  recalling_firm: null,
  recall_reason: "Product Contamination",
  classification: null,
  severity: null,
  status: "Public Health Alert",
  recall_date: null,
  reported_at: "2026-08-20",
  source_updated_at: "2026-08-21",
  distribution_pattern: "Nationwide",
  product_code_info: null,
  product_items: [],
  establishment_numbers: [],
  source_documents: [
    "https://www.fsis.usda.gov/sites/default/files/distro_list/example.pdf",
  ],
  states: [],
  upc_codes: [],
  lot_numbers: [],
  source_url: "https://www.fsis.usda.gov/recalls-alerts/example",
};
